/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Matematicas;

/**
 *
 * @author diego
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("DETERMINANTES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        x1 = new javax.swing.JTextField();
        y1 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        z3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMAS DE ECUACIONES 3X3 ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DETERMINANTES");

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGLA DE CRAMER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 74, 57));

        y1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 12, 74, 57));

        z1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        z1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 12, 74, 57));

        x2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, 74, 57));

        y2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 87, 74, 57));

        z2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        z2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 87, 74, 57));

        ti1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ti1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 12, 74, 57));

        ti2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ti2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 87, 74, 57));

        y3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 162, 74, 57));

        ti3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ti3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(ti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 162, 74, 57));

        x3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 162, 74, 57));

        z3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        z3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 162, 74, 57));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 430, 310));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Y");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Z");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 160, -1));

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 300, 160, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 210));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        jLabel5.setText("TI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Diego Diaz De La Concha");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        float X1 = Float.parseFloat(x1.getText());
        float X2 = Float.parseFloat(x2.getText());
        float X3 = Float.parseFloat(x3.getText());
        
        float Y1 = Float.parseFloat(y1.getText());
        float Y2 = Float.parseFloat(y2.getText());
        float Y3 = Float.parseFloat(y3.getText());
        
        float Z1 = Float.parseFloat(z1.getText());
        float Z2 = Float.parseFloat(z2.getText());
        float Z3 = Float.parseFloat(z3.getText());
        
        float TI1 = Float.parseFloat(ti1.getText());
        float TI2 = Float.parseFloat(ti2.getText());
        float TI3 = Float.parseFloat(ti3.getText());
        
        
        float detA = ((X1 * Y2 * Z3)+(Y1 * Z2 * X3)+(Z1 * X2 * Y3))-((Y1 * X2 * Z3)+(X1 * Z2 * Y3)+(Z1 * Y2 * X3));
        
        float detAx = ((TI1 * Y2 * Z3)+(Y1 * Z2 * TI3)+(Z1 * TI2 * Y3))-((Y1 * TI2 * Z3)+(TI1 * Z2 * Y3)+(Z1 * Y2 * TI3));
        float detAy = ((X1 * TI2 * Z3)+(TI1 * Z2 * X3)+(Z1 * X2 * TI3))-((TI1 * X2 * Z3)+(X1 * Z2 * TI3)+(Z1 * TI2 * X3));
        float detAz = ((X1 * Y2 * TI3)+(Y1 * TI2 * X3)+(TI1 * X2 * Y3))-((Y1 * X2 * TI3)+(X1 * TI2 * Y3)+(TI1 * Y2 * X3));
        
        float x = detAx/detA;
        float y = detAy/detA;
        float z = detAz/detA;
        
        String respuesta = "RESULTADOS FINALES: \n"+"X: "+x+"\nY: "+y+"\nZ: "+z;
        
        area.setText(respuesta);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        x1.setText("");
        x2.setText("");
        x3.setText("");
        
        y1.setText("");
        y2.setText("");
        y3.setText("");
        
        z1.setText("");
        z2.setText("");
        z3.setText("");
        
        ti1.setText("");
        ti2.setText("");
        ti3.setText("");
        
        area.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
